/**
 * TAU Tools
 * https://github.com/arazimproject/tau-tools
 */

/**
 * Available at https://arazim-project.com/data/courses.json.
 * Generated by the collect.py script.
 * Taken from the university's course search website.
 * A map from a course ID (like "03661111") to the collected course info throughout all time (since 1999).
 */
interface AllTimeCourses {
  [courseId: string]: AllTimeCourseInfo | undefined
}

/**
 * Available at https://arazim-project.com/data/courses-{SEMESTER}.json for a valid SEMESTER, such as 2024a.
 * Generated by the courses.py script.
 * Taken from the university's course search website.
 * A map from a course ID (like "03661111") to the collected course info in the given semester.
 */
interface SemesterCourses {
  [courseId: string]: SemesterCourseInfo | undefined
}

/**
 * Available at https://arazim-project.com/data/plans-{YEAR}.json for a valid YEAR, such as 2024.
 * Generated by the plans.py script.
 * Taken from the university's course search website.
 * A map from a faculty (like "הפקולטה למדעים מדויקים") to a map from a plan name (like "תוכנית דו-חוגית במתמטיקה ובמדעי המחשב") to the plan's info.
 */
interface SemesterPlans {
  [faculty: string]:
    | {
        [plan: string]: YearPlanInfo | undefined
      }
    | undefined
}

/**
 * Available at https://arazim-project.com/data/info.json.
 * Generated manually.
 */
interface GeneralInfo {
  /** The current semester at Tel Aviv University, like "2025a". */
  currentSemester?: string
  semesters?: {
    [semester: string]: GeneralSemesterInfo | undefined
  }
}

interface AllTimeCourseInfo {
  /** The course's name (the latest one, if changed). */
  name?: string
  /** The course's faculty (the latest one, if changed). */
  faculty?: string
  /** The semesters in which the course was taught (like "2024a"). */
  semesters?: string[]
  /** Everyone who has ever taught this course. */
  lecturers?: string[]
}

/** All information about the course in the given semester. */
interface SemesterCourseInfo {
  /** The course's name. */
  name?: string
  /** The course's faculty. */
  faculty?: string
  /** The course's exams and their dates. */
  exams?: SemesterCourseExamInfo[]
  /** The course's groups and their lessons & lecturers. */
  groups?: SemesterCourseGroupInfo[]
  /** Links to the course's exams in the given semester in the Moodle. Currently only available for exact sciences. */
  exam_links?: string[]
  /** The prerequisites to the course */
  prerequisites?: SemesterCoursesPrerequisiteCourses
}

/** A nested tree of requirements, each either "any" or "all". */
interface SemesterCoursesPrerequisiteCourses {
  kind?: "any" | "all"
  courses?: (string | SemesterCoursesPrerequisiteCourses)[]
  parallel?: SemesterCoursesPrerequisiteCourses
}

/** All information about a given course's exam. */
interface SemesterCourseExamInfo {
  /** Whether's it's מועד א or מועד ב etc. */
  moed?: string
  /** The date string of the exam (like "13/02/2025"). */
  date?: string
  /** The hour string of the exam (like "09:30"). */
  hour?: string
  /** The type of the exam (like "בחינה סופית"). */
  type?: string
}

/** All information about a given course's group. */
interface SemesterCourseGroupInfo {
  /** The group's ID, for example "01". */
  group?: string
  /** The groups's lecturer separated by commas. */
  lecturer?: string | null
  /** The group's lessons and their time & locations. */
  lessons?: SemesterCourseGroupLessonInfo[]
}

/** All information about a given group's lesson. */
interface SemesterCourseGroupLessonInfo {
  /** The day of the lesson (like "ד"). */
  day?: string
  /** The time string of the lesson (like "15:00-18:00"). */
  time?: string
  /** The building of the lesson (like "מכסיקו"). */
  building?: string
  /** The room of the building (like "207א"). */
  room?: string
  /** The type of the lesson (like "תרגיל"). */
  type?: string
}

/** All information about a study plan in a given year. */
interface YearPlanInfo {
  /** A mapping from the category's name (like "שנה א' - סמסטר א' - קורסי חובה") to the category's info. */
  [category: string]: YearPlanCategoryInfo | undefined
}

/** All information about a category in a study plan. */
interface YearPlanCategoryInfo {
  /** The courses in the category. */
  courses: {
    [courseId: string]: YearPlanCourseInfo | undefined
  }
  /** The total courses needed from this category. */
  count: number
}

/** All information about a course in a study plan. */
interface YearPlanCourseInfo {
  /** The course's ID, like "03661111". */
  id?: string
  /** The course's weight (שעות סמסטריאליות). */
  weight?: number
}

/** General information about the given semester. */
interface GeneralSemesterInfo {
  /** The start date of the semester (e.g. March 16, 2025 00:00:00). */
  startDate: string
  /** The end date of the semester (e.g. July 2, 2025 00:00:00). */
  endDate: string
}

/** All bidding statistics throughout the years. */
interface AllTimeBiddingInfo {
  [courseId: string]: {
    [semester: string]: {
      [group: string]: GroupBiddingInfo[]
    }
  }
}

/** Statistics about bidding of a specific group of a course in some semester. */
interface GroupBiddingInfo {
  /** If the bidding was per-faculty, these statistics are only for the given faculty. */
  faculty?: string
  /** The maximal bid amount someone did. */
  maximal: number
  /** The minimal bid amount of someone who received the group. */
  minimal: number
  /** The number of people who wanted the group. */
  wanted: number
  /** The numbers of people who received the group. */
  received: number
  /** The number of available spots in this current bidding run. */
  run_available: number
  /** The total number of available spots in this group. */
  total_available: number
}
